### ISSUE TITLE
GEDCOM 5.5 to GEDCOM X JSON conversion

### ISSUE THREAD

**Issue by tomeara** [rootsdev/gedcomx-js#27]
I've been looking for a conversion tool to transform straight GEDCOM 5.5 into GEDCOM X according to the [GEDCOM X v1 JSON serialization format](https://github.com/FamilySearch/gedcomx/blob/master/specifications/json-format-specification.md). I've seen a couple of other JS projects (as well as the core Java implementation) but I want to output directly to JSON without .gedx being an intermediate format.

So I have 2 questions:

1. I've been spending a bit of time googling for it, but is there already a GEDCOM X conversion tool that does what I want? I do not want to duplicate work, but there does not seem to be.
1. If not, this project looks to be a great library to use to model the schema, but I'm unsure to whether or not a conversion feature would be desired here. I was planning on writing it separately, but is a conversion feature something that you'd like to be a part of this project?

**Comment by justincy** [comment]
I would love to see a tool that converts GEDCOM directly to GEDCOM X JSON but this repo isn't the proper place for it. What's your use case? Do you have a specific language or environment in mind where it needs to run? 

I was thinking about this over the holidays. I'd love to have a pure JS lib so that it can be run client or server side. It would be published on npm with a cli wrapper. There would also be gh-pages where devs can use the tool for testing or perform quick one-off conversions.

**Comment by tomeara** [comment]
Yeah, I didn't think this repo would be the right place either, but I wanted to make sure that I didn't conflict with your work. :)

I have a .ged export from a older version from "Family Tree Maker" circa late 90s, and I want to get that export up-to-date with the most current spec; that looks to be GEDCOM X from everything I'm learning. Also, I want to get the data into a format (JSON) that I prefer working with. 

Once I have that converted, I would like to start building another tool like [Gramps](https://gramps-project.org/) in [Electron](https://github.com/electron/electron). Nothing against Gramps; it looks like they've done great work. I just think it would be a fun side-project, and I definitely want to move our family's data to a more open solution in the same vein.

I'd certainly be into a cli package that would convert GEDCOM 5.5, and that's where I've been going with it so far. I've been building out the parsing module at the moment, but I haven't pushed anything up yet since my test fixtures are from my own data. If you could point me to a de-facto .ged file that I should use as a source, that would be great! I have run across .ged files like this: https://github.com/FamilySearch/Gedcom/blob/master/src/test/resources/Case001-AddressStructure.ged, but that doesn't seem to be as encompassing of different use cases. I'll also need to cover some edge cases that the FTM output gives me, but I can handle that fixture data if there isn't a good public source to use from them.

Once I get things pushed up, I'd love to get your input on what I have.

**Comment by justincy** [comment]
Regarding an Electron app, checkout work being done by John Clark on [Treehub](https://github.com/treehub-eng/treehub).

For GEDCOM test files, I'm not aware of anything beyond what a Google search would reveal. Oddly enough, I've never done any programmatic processing of GEDCOM files.

Keep me in the loop.
